name: Build and Deploy Java App

on:
  push:
    branches: [ "main" ]   # Trigger on main branch push (change if needed)
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    # 4. Build with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # 5. Verify WAR output
    - name: List target files
      run: ls -l target
   
    - name: Check WAR file existence
      run: |
          if [ ! -f target/*.war ]; then
          echo "ERROR: WAR file not found!"
          exit 1
          fi
          
    # 6. Upload WAR to Jenkins
    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
          url: "https://tigers-palestinian-layer-itunes.trycloudflare.com"
          user: "${{ secrets.JENKINS_USER }}"
          token: "${{ secrets.JENKINS_API_TOKEN }}"
          job: "Project2"
          parameters: "WAR_FILE=target/*.war"
